### ISSUE TITLE
Crash on closing QGIS

### ISSUE THREAD

**Issue by TNogatz** [lcalisto/qgis-finddataset-plugin#12]
Everytime I close QGIS with the plugin installed QGIS crashes. 
QGIS version: 3.4, platform: Windows 7
After deinstallation of FindDataset QGIS does not crash on closing.

**Comment by lcalisto** [comment]
Can you please specify the full QGIS version? is it 3.4.11?

**Comment by TNogatz** [comment]
Hi Icalisto,
it is the same problem with both installed versions QGIS 3.4.11 and 3.8.2

**Comment by lcalisto** [comment]
I can reproduce it also on both mac and linux. I'm busy the next days but I'll try to fix it asap.

**Comment by lcalisto** [comment]
It looks this is no longer happening on the new versions. Closing this issue for the moment
