### ISSUE TITLE
offer region search

### ISSUE THREAD

**Issue by riccardoklinger** [lcalisto/qgis-finddataset-plugin#2]
currently your're offering point based search. What about using a bbox extent to search in as well?

**Comment by lcalisto** [comment]
Yes this could be interesting.

**Comment by andremano** [comment]
This is very interesting!

**Comment by lcalisto** [comment]
Added region search in the latest commit. Still needs some final testing.

**Comment by lcalisto** [comment]
I'm closing this issue since I believe it's solved now.
