### ISSUE TITLE
catalog function

### ISSUE THREAD

**Issue by riccardoklinger** [lcalisto/qgis-finddataset-plugin#3]
It would be a nice option to export the find results as a polygon layer:
spatial extend of finds as a rectangle, name, path, and concatenated list of fields as well as other data as attributes.
This would makes it easy to create a somewhat data catalog of all the datasets on your folder for easy search and spatial selection options.

**Comment by riccardoklinger** [comment]
I am already looking into this: added a new export results button, connected, reading out results and storing extents of results together with other data in a separate memory vector layer...

**Comment by riccardoklinger** [comment]
first version is ready.
![grafik](https://user-images.githubusercontent.com/7377897/48984374-1683e400-f0fb-11e8-83ef-b74ebcf1e9ef.png)

**Comment by riccardoklinger** [comment]
and here the changes to the gui:
![grafik](https://user-images.githubusercontent.com/7377897/48984385-2c91a480-f0fb-11e8-8097-b85e2d3bb6fb.png)

**Comment by riccardoklinger** [comment]
function is in commit 074dd3cc11f269ac3b1a25dbd892f2227911e125 and I've created a merge request.

**Comment by lcalisto** [comment]
I believe this is done in your commit. I tested it and it works.

**Comment by lcalisto** [comment]
The catalog layer (generated by the export results) is using EPSG 4326, nevertheless the CRS is not defined for this layer. If a user is working on a different CRS the layer is loaded with the project CRS and not as 4326. I think I can fix the problem easily by assigning 4326 when defining the catalog layer, I'll try.

**Comment by lcalisto** [comment]
It was easier that what I thought. Its fixed in the latest commit https://github.com/lcalisto/qgis-finddataset-plugin/commit/d9135c02cd5c11675114e7a1b3deba3898775a46
