### ISSUE TITLE
show coordinates in EPSG 4326

### ISSUE THREAD

**Issue by riccardoklinger** [lcalisto/qgis-finddataset-plugin#5]
As you do have the field to show coordinates I would prefer to show them in EPSG4326 and not in tha map CRS.
What is your opinion on this @lcalisto ?

**Comment by lcalisto** [comment]
I have thought about this. Currently the plugin searches all datasets regardless their CRS. When a user captures the point, I strongly believe we should display the captured point in the coordinate system the user is working with. It might be confusing for some users to capture a point in one CRS and the plugin displays the captured coordinate in a different CRS. In the end all datasets are searched independent on their CRS. 

Perhaps you can describe this better?

**Comment by andremano** [comment]
I agree with Luis. I also favor keeping the coordinates in the CRS the user is working with.

**Comment by riccardoklinger** [comment]
Okay. So lets close this now or maybe, as it is a simple text field show both: project crs coordinates as well as 4326 coords?

**Comment by lcalisto** [comment]
Lets close it for now. We can reopen later more people think we should open it.
