### ISSUE TITLE
allow users to select all

### ISSUE THREAD

**Issue by riccardoklinger** [lcalisto/qgis-finddataset-plugin#8]
in the current release you need to click on every item separately. I would like to be able to select all items in the result list,

**Comment by lcalisto** [comment]
We can add one more button, but if you select one item and slide the mouse then you can select all. It's very simple:

![select](https://user-images.githubusercontent.com/4139084/49222846-512c9b80-f3dd-11e8-940e-0dcd250e467c.gif)

**Comment by riccardoklinger** [comment]
Haven't seen this. Works perfectly.
